### PR TITLE
Release 2.0 sheets

### PR DESCRIPTION
**Pull request by arhajiismael206**
SDK changes to sheet resource to reflect API 2.0 changes

### CODE REVIEW

**Comment by brettbatie** [comment]
Ahmad, 

Below is the list of things I noticed when looking over the code changes that you made. Overall you did good for just jumping into the SDK & Java. We definitely have a high standard for the SDK so please don't take the below list personally. Also, Please make sure to write unit tests for all new code that is added to the SDK. 

* Unit Tests Fail
* Create a model for the PagingParameters and use that where appropriate. Give this class a toString() or toQueryString() method and delete the `handlePaginationQueryParameters` method.
* where is the unit test for `generateCommaSeparatedListFromList`?
*  The methods `generateQueryString`, `generateCommaSeparatedListFromEnumSet`, `generateCommaSeparatedListFromList` all need to have their strings URLEncoded.
* merge `generateCommaSeparatedListFromList` and `generateCommaSperatedListFromEnumSet` into a method named `generateCommaSeperatedList(Set)`.
* Use StringBuilder instead of concatenation when needing to concatenate multiple times (in a loop), it is more efficient.
* Remove `generateQueryString` and use OAuthFlowImpl.generateURL, but move that method to a Util class.
* Refactor CELLLINKS to CELL_LINKS - this is more readable and following the convention for constants: http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-135099.html#367
* What happens when we serialize the Recipient object and both the Recipient.email & Recipient.groupId are set?  Instead create an interface Recipient and create the classes RecipientEmail & RecipientGroup to inherit from Recipient.
* Looks like we never setup a good unit test for testSendSheet(). Can you change this to validate that the json is generated correctly for an email?
* You have the code: `private List<AttachmentType> effectiveAttachmentOptions;`. Can you instead change this to be `private EnumSet<AttachmentType> effectiveAttachmentOptions;`?
* In the code `public void setType(String type) {`, make the type an enum.

**Comment by arhajiismael206** [comment]
Brett,

I made most of the changes based on your feedback. The only thing that I left out was changing the "type" field within the Source object. I left it as a String. Based on the documentation, there isn't a source type enum which is why I didn't change it to an enum.

**Comment by brettbatie** [comment]
Let me try to sway your opinion on the "type" parameter. 

Currently the function looks like: `public void setType(String type)`. So, if I was a user and wanted to know if if the type was a template or a sheet. I would need to write  `if(getType() == "sheet"){}elseif(getType() == "template"){}`. This has two flaws: 1. I would have to go to the api documentation to determine what types are available. 2. The user could easily put a typo in the string like `if(getType() == "temple").

I think it would be nice to instead let the user do something like: `if(getType() == SourceType.Sheet)`, where SourceType is an enum. This way the IDE will tell them what their two options are so that they don't have to look at the api docs and it will require they use an valid enum  or it will not compile. Plus, an enum is an object and can be serialized as a string so it is the best of both worlds. Take a look at the ObjectInclusion Enum and notice how it is technically Strings that are being stored in the Enum.

**Comment by brettbatie** [comment]
As we discussed, you can use a Set for the parameter on the generateCommaSeperatedList method instead of a Collection. There are two uses of the function one is currently passing in a List but should instead be passing in a Set and the other is passing in a EnumSet which is also a Set.

**Pull request merged**
